hotfix: actions fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -2,7 +2,7 @@ name: Deploy to EC2
 
 on:
   push:
-    branches: [ dev ]
+    branches: [dev]
 
 jobs:
   deploy:
@@ -34,55 +34,53 @@ jobs:
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_KEY }}
           script: |
-                    set -e  # Exit on first error
-                    
-                    echo "** Connected to EC2 server **"
-                    
-                    # Ensure Git is installed
-                    if ! command -v git &> /dev/null
-                    then
-                    echo "Git could not be found, installing..."
-                    sudo apt-get update && sudo apt-get install git -y
-                    fi
-                    
-                    # Check if /app is a valid Git repository
-                    if [ -d "/app/.git" ]; then
-                    echo "** /app is a Git repository. Fetching latest changes... **"
-                    cd /app
-                    # Ensure the repository is set to the correct remote and branch
-                    git remote set-url origin git@github.com:RudreshNarwal/folo.django.git
-                    git fetch origin dev
-                    git reset --hard origin/dev
-                    git clean -fd
-                    else
-                    if [ -d "/app" ]; then
-                    echo "** /app exists but is not a Git repo. Removing... **"
-                    sudo rm -rf /app
-                    fi
-                    # Clone the repository as /app did not exist or was not a Git repository
-                    echo "** Creating /app directory... **"
-                    mkdir -p /app
-            # Adjust the permission as needed. Example: making the current user the owner
-            # This step assumes the current user has sufficient permissions to do so
-                    sudo chown $USER:$USER /app
-                    sudo chmod 755 /app
-                    echo "** Cloning repository into /app... **"
-                    pwd
-                    ls -l
-                    git clone -b dev git@github.com:RudreshNarwal/folo.django.git /app
-                    fi
-                    
-                    cd /app
-                    
-                    mkdir -p ./.envs/.production/
-                    echo "${{ env.ENV_BASE64_DJANGO }}" | base64 --decode > combined.env.django
-                    cp combined.env.django ./.envs/.production/.django
+            set -e  # Exit on first error
+
+            echo "** Connected to EC2 server **"
+
+            # Ensure Git is installed
+            if ! command -v git &> /dev/null
+            then
+                echo "Git could not be found, installing..."
+                sudo apt-get update && sudo apt-get install git -y
+            fi
+
+            # Check if /app is a valid Git repository
+            if [ -d "/app/.git" ]; then
+              echo "** /app is a Git repository. Fetching latest changes... **"
+              cd /app
+              # Ensure the repository is set to the correct remote and branch
+              git remote set-url origin git@github.com:RudreshNarwal/folo.django.git
+              git fetch origin dev
+              git reset --hard origin/dev
+              git clean -fd
+            else
+              if [ -d "/app" ]; then
+                echo "** /app exists but is not a Git repo. Removing... **"
+                sudo rm -rf /app
+              fi
+              echo "** Creating /app directory... **"
+              mkdir -p /app
+              # Adjust the permission as needed. Example: making the current user the owner
+              # This step assumes the current user has sufficient permissions to do so
+              sudo chown $USER:$USER /app
+              sudo chmod 755 /app
+              echo "** Cloning repository into /app... **"
+              pwd
+              ls -l
+              git clone -b dev git@github.com:RudreshNarwal/folo.django.git /app
+            fi
+
+            cd /app
+            
+            mkdir -p ./.envs/.production/
+            echo "${{ env.ENV_BASE64_DJANGO }}" | base64 --decode > combined.env.django
+            cp combined.env.django ./.envs/.production/.django
 
             # Here, include any steps required to prepare the application environment,
             # such as running migrations, compiling assets, etc.
-                    
-                    echo "** Building and starting Docker containers... **"
-                    sudo docker compose -f production.yml up --build -d --remove-orphans || (echo "** Docker Compose failed! **" && exit 1)
-                    
-                    echo "** Deployment completed successfully! **"
-      
+
+            echo "** Building and starting Docker containers... **"
+            sudo docker compose -f production.yml up --build -d --remove-orphans || (echo "** Docker Compose failed! **" && exit 1)
+
+            echo "** Deployment completed successfully! **"
